---
- name: Install Python3.10.6
  become: true
  ansible.builtin.apt:
    name: python3.10
    state: latest
    install_recommends: false
    update_cache: true

- name: Install pip3
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: latest
    install_recommends: false
    update_cache: true

- name: Install dependencies
  become: true
  pip:
    name:
      - mastodon.py
    state: present