---
- name: Set up SSH directory
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: Create SSH private key file
  ansible.builtin.copy:
    content: "{{ ssh_key }}"
    dest: ~/.ssh/id_rsa
    mode: '0600'

- name: Add newline to id_rsa file
  blockinfile:
    path: ~/.ssh/id_rsa
    marker: ""
    insertafter: EOF
    block: |

- name: Check directory existence
  stat:
    path: "{{ mountpoint }}/{{ code_directory }}"
  register: dir_check

- name: Clone repository from Github
  shell: |
    cd /data 
    git clone {{ repo }}
  when: dir_check.stat.exists is not defined or not dir_check.stat.exists

- name: Remove SSH private key file
  ansible.builtin.file:
    path: ~/.ssh/id_rsa
    state: absent