---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name: ["xfsprogs"]
    state: latest
    install_recommends: false
    update_cache: true

- name: Make file system
  become: true
  community.general.filesystem:
    fstype: xfs
    dev: "{{ device }}"
  when: item.device is defined

- name: Checking folders
  become: true
  ansible.builtin.stat:
    path: "{{ mountpoint }}"
  register: directory_stats

- name: Create directory
  become: true
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    recurse: true
    state: directory
  when: directory_stats.stat.exists == false

- name: Mount device
  become: true
  ansible.posix.mount:
    path: "{{ mountpoint }}"
    src: "{{ device }}"
    fstype: xfs
    state: mounted
  when: device is defined

- name: Change ownership of /data
  become: true
  become_user: root
  file:
    path: "{{ mountpoint }}"
    owner: ubuntu
    recurse: yes