# - hosts: localhost
#   vars_files:
#     - host_vars/nectar.yaml
#   gather_facts: true

#   roles:
#     - role: openstack-common
#     - role: openstack-volume
#     - role: openstack-security-group
#     - role: openstack-instance

- hosts: COMP90024
  vars_files:
    - host_vars/instances.yaml
  gather_facts: true

  roles:
    # - role: instances-format-volume
    # - role: instances-install-software
    - role: instances-pull-code
    - role: instances-store-data


    TRY TO PULL CODE NOW BUT NEED TO EXPORT PRIVATE KEY AYE
    I JUST CREATED A COPY SCRIPT AND SAVE IT IN HARVESTED_DATA.PY