availability_zone: melbourne-qh2-uom
instance_flavor: uom.mse.1c4g
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: cloud
instances:
- name: instance-1
  volumes:
  - instance-1-vol
- name: instance-2
  volumes:
  - instance-2-vol
- name: instance-3
  volumes:
  - instance-3-vol
security_groups:
- description: Security group for SSH access
  name: ssh
  port_range_max: 22
  port_range_min: 22
  protocol: tcp
  remote_ip_prefix: 0.0.0.0/0
- description: Security group for HTTP
  name: http
  port_range_max: 80
  port_range_min: 80
  protocol: tcp
  remote_ip_prefix: 0.0.0.0/0
volumes:
- vol_name: instance-1-vol
  vol_size: 50
- vol_name: instance-2-vol
  vol_size: 50
- vol_name: instance-3-vol
  vol_size: 50
